logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8076
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: "Impulso Database: DEV"
  datasource:
    url: jdbc:postgresql://localhost:5432/impulso_test_2
    username: postgres
    password: coffee2sweet
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-main.yaml