logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8077
spring:
  config:
    activate:
      on-profile: test
  application:
    name: "Impulso Database: TEST"
  datasource:
    url: jdbc:postgresql://localhost:5432/impulso_db_test
    username: postgres
    password: coffee2sweet
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
